In [1]:
import pandas as pd
from glob import glob

file_names = sorted(glob('dataset/2022*.xls'))
file_names

['dataset\\2022년 01월  교통카드 통계자료.xls',
 'dataset\\2022년 02월  교통카드 통계자료.xls',
 'dataset\\2022년 03월  교통카드 통계자료.xls',
 'dataset\\2022년 04월  교통카드 통계자료.xls',
 'dataset\\2022년 05월  교통카드 통계자료.xls',
 'dataset\\2022년 06월  교통카드 통계자료.xls',
 'dataset\\2022년 07월  교통카드 통계자료.xls',
 'dataset\\2022년 08월  교통카드 통계자료.xls',
 'dataset\\2022년 09월  교통카드 통계자료.xls']

In [2]:
sheets = ['버스정류장별 이용현황', '지하철 노션별 역별 이용현황', '지하철 유무임별 이용현황', '지하철 시간대별 이용현황']

In [3]:
df_columns = ['사용월', '노선ID', '노선번호', '노선명', '버스정류장ID', '버스정류장명', '승차승객수', '하차승객수','작업일시']

In [4]:
# df = pd.read_excel("엑셀 파일 경로", sheet_name = "불러올 시트 이름")
raw = pd.DataFrame(columns=df_columns)
for file_name in file_names:
    df = pd.read_excel(file_name, sheet_name=sheets[0])
    raw = pd.concat([raw, df], ignore_index=True)
    print(raw.shape)

(39159, 9)
(78241, 9)
(117324, 9)
(157534, 9)
(197862, 9)
(238399, 9)
(278452, 9)
(318526, 9)
(358608, 9)

In [69]:
raw.to_csv("data/2022_tmoney.csv", index=False)

In [70]:
pd.read_csv("data/2022_tmoney.csv")

,사용월,노선ID,노선번호,노선명,버스정류장ID,버스정류장명,승차승객수,하차승객수,작업일시
0,2022-01,11110897,0017,0017번(청암동~이촌동),1,청암자이아파트,453,12,2022-02-03 08:49:57
1,2022-01,11110897,0017,0017번(청암동~이촌동),2,청암동강변삼성아파트,"1,328",43,2022-02-03 08:49:57
2,2022-01,11110897,0017,0017번(청암동~이촌동),3,청심경로당,"2,420",45,2022-02-03 08:49:57
3,2022-01,11110897,0017,0017번(청암동~이촌동),4,원효2동주민센터,"4,196",95,2022-02-03 08:49:57
4,2022-01,11110897,0017,0017번(청암동~이촌동),5,산천동,"5,255",206,2022-02-03 08:49:57
...,...,...,...,...,...,...,...,...,...
358603,2022-09,11110729,중랑02,중랑02(진로아파트~한신아파트),22,서일대정문,141,"6,056",2022-10-03 09:13:34
358604,2022-09,11110729,중랑02,중랑02(진로아파트~한신아파트),23,새마을금고,586,"5,616",2022-10-03 09:13:34
358605,2022-09,11110729,중랑02,중랑02(진로아파트~한신아파트),24,공판장,43,"7,038",2022-10-03 09:13:34
358606,2022-09,11110729,중랑02,중랑02(진로아파트~한신아파트),25,진주빌라.바다약국,29,"9,723",2022-10-03 09:13:34
358607,2022-09,11110729,중랑02,중랑02(진로아파트~한신아파트),26,진로아파트앞.종점,72,"3,003",2022-10-03 09:13:34